### ISSUE TITLE
Spawning just the configured gen pokemons

### ISSUE THREAD

**Issue by ritwickdsouza** [oliver-ni/poketwo#101]
**Is your feature request related to a problem? Please describe.**
Most users on our discord channel only know pokemon from gen 1/2/3, so it becomes difficult for them to catch a lot of pokemon.

**Describe the solution you'd like**
Ability to configure a set of generations so pokemon only from those generations spawn.

:)

**Comment by kyle-he** [comment]
Since pokemon are traded across servers, it would be unfair to allow different servers to have different spawn rates. I will be closing this issue for now.
