### ISSUE TITLE
Deleting bot messages

### ISSUE THREAD

**Issue by dylithian** [oliver-ni/poketwo#103]
**Is your feature request related to a problem? Please describe.**
Poketwo's messages tend to interrupt the flow of conversation. Not a major problem.

**Describe the solution you'd like**
If messages were deleted after the relevant user's next message (so for example, level up alerts would delete after the person who the alert was for sent their next message), it would let those messages appear in the short term while removing bot-spam in the long term.

**Additional context**
It might also be a good idea to have pokemon spawns delete like, ten seconds after the pokemon is caught.

**Comment by NathNathNathNath** [comment]
I like the idea of deleting the level-up messages in the way you describe, though I think it should be toggle-able if implemented.

**Comment by kyle-he** [comment]
That actually is toggle-able both user side and server wide! You can you run `p!config help` to see more information.

**Comment by NathNathNathNath** [comment]
@kyle-he How so? I don't believe this person was talking about the serversilence feature, if that is what you mean. They are suggesting an enhancement: the levelup messages will still appear, but will auto-delete once the user they are intended for sends another message

**Comment by dylithian** [comment]
> 
> 
> @kyle-he How so? I don't believe this person was talking about the serversilence feature, if that is what you mean. They are suggesting an enhancement: the levelup messages will still appear, but will auto-delete once the user they are intended for sends another message

Yes. This is correct. I'll investigate, but this is a feature based on features present in the [Rod of Discord D&D Bot](https://rodbot.io). Messages can be sent with that bot and then delete after a preset time.

**Comment by oliver-ni** [comment]
Hi, thanks for your suggestion.

As I'm currently working on a full rewrite, and because this is a rather minor enhancement with a non-trivial implementation, i'll be keep this closed for now.

Feel free to reopen / open a new issue when the rewrite is out
