### ISSUE TITLE
Balance shiny hunt rate 

### ISSUE THREAD

**Issue by Eydahn8** [oliver-ni/poketwo#104]
**Is your feature request related to a problem? Please describe.**
Shiny rates are not balanced. The spawn of a common pokemon is higher than 0.2111%, while that of mythical, legendaries and ultra bests does not exceed 0.0050%, so I don't understand why is applied the 1/4096 rule, if pokemon do not spawn at the same percentage.

**Describe the solution you'd like** 
Even on pokemon go this function has been balanced, there should be separate shiny rates for common pokemon, mythical, legendaries and ultra beasts, based on the percentage of spawn and not on a general rule.

If in this case redeems were a problem, it would be possible to add a limit of 5 redeems on specific pokemon per month, in addition to the limit of 20 monthly redeems.

**Additional context**
Thanks for your work and sorry for my english, I'm italian

**Comment by kyle-he** [comment]
Shiny rates are the same as the canon. https://bulbapedia.bulbagarden.net/wiki/Shiny_Pok%C3%A9mon#:~:text=A%20Shiny%20Pok%C3%A9mon%20(Japanese%3A%20%E8%89%B2,is%20usual%20for%20its%20species.

In addition, this allows for different shinies to have different levels of demand (as expected) which is also beneficial for the economy.
