### ISSUE TITLE
I can’t use P!pokemon

### ISSUE THREAD

**Issue by amwildkitty** [oliver-ni/poketwo#107]
I type p!pokemon and no Pokémon show up I did this multiple times

![image](https://user-images.githubusercontent.com/75462229/104452591-37c11c00-5571-11eb-8f42-adea4597cb73.jpeg)

**Comment by Bemon101** [comment]
Yup me to I can't open p!pokemon

**Comment by Shirra2006** [comment]
I don't know but it still works fine for me, maybe it was because the prefix is changed in that server?

**Comment by oliver-ni** [comment]
Should be fixed, please DM me if it's still not working.
