### ISSUE TITLE
Sorting (dex/pokemon) By Amount Caught

### ISSUE THREAD

**Issue by DwarvenCoalhome** [oliver-ni/poketwo#109]
I sometimes wonder what Pokémon I’ve caught the most of. I’ll open the dex and scroll and look, or I’ll look up the individual dex entries of what I assume I may have the most of to compare. Something I would do before I started releasing for pc was also p!order dex and look to what I seemed to have the most of.

When it comes to things like this, especially when it comes to trying for catch milestones, I think a way to sort your Pokémon and/or the Pokédex by number caught would be a good idea. That way, you can easily check
1-) Which Pokémon you’ve caught the most of
2-) Which Pokémon you’re close to milestones on
3-) Which Pokémon you’ve caught none of 

perhaps it could include something like Caught- or Caught+ (Similar to IV sorting) to filter from most caught first or least caught first.

I feel that this is a feature that many people could make use of, and I’ve had it on my mind for quite a while now. Love the bot, and keep up the great work! <3

**Comment by michaelsong4399** [comment]
Hello Dwarven, you can try the following commands: `p!dex --orderd` to view most caught Pokemons, `p!dex --unc` to view your uncaught Pokemons. As far as Pokemon milestones, feel free to try the new reaction-scrolling feature and scrll through the most caught Pokemons and check yourself. I hope this helps.

**Comment by DwarvenCoalhome** [comment]
I didn’t see these on lists of commands I looked at, so they’re a big help. Thank you!

**Comment by michaelsong4399** [comment]
If you do `p!help dex`, you can see them listed in the Signatures. You could try that.
