### ISSUE TITLE
Allow evolution of multiple Pokémon at once

### ISSUE THREAD

**Issue by DevilJamJar** [oliver-ni/poketwo#113]
**Is your feature request related to a problem? Please describe.**
At times, it may be necessary to evolve multiple Pokémon quickly, for example wanting to change 5 Pokémon of the same species into their evolved counterparts, or any grouping of Pokémon.

**Describe the solution you'd like**
An implementation similar to `p!battle add`, using `commands.Greedy` to convert the args, and evolve each one, or none if any of them cannot be evolved. Example: `p!evolve 58 295 1026 5`, which would evolve all 4 Pokémon, or throw an error if any are unavailable for evolution.

**Additional context**
I attempted a PR implementing this, but was unsure how to format the multiple Pokémon evolutions into one embed without becoming overwhelmingly large, so I suppose I'll leave that up for debate.

**Comment by oliver-ni** [comment]
This sounds like a good enhancement.

> I attempted a PR implementing this, but was unsure how to format the multiple Pokémon evolutions into one embed without becoming overwhelmingly large, so I suppose I'll leave that up for debate.

I think it's fine to add a field for each pokémon. It might end up a bit large, but it should be fine. The only thing is just make sure to stay under the field limit.

Alternatively, could also implement a thing where >20 pokémon doesn't send an embed and sends a normal message instead. (or an embed with description instead of fields.)

**Comment by DevilJamJar** [comment]
Great, thanks a lot for the input, i’ll get on with this, but in terms of the embed formatting, how would I go about changing the thumbnail? At the moment the URL is set to that of the Pokémon, but how would that be handled for multiple?

I was wondering if maybe it would be better to use the Pokémon emotes, as used in market and auction commands, for each field when there is more than one Pokémon to evolve, instead of using the sprite URLs.

**Comment by oliver-ni** [comment]
Using the Pokémon emotes could be a good idea. Either way I don't think the thumbnail is necessary if it's with multiple pokémon.
