### ISSUE TITLE
No background for specific pokemon

### ISSUE THREAD

**Issue by NathNathNathNath** [oliver-ni/poketwo#114]
**Describe the bug**
Since the restart (moving to a more performant server), a specific pokemon doesn't have a background - Baltoy.

**To Reproduce**
See a Baltoy spawn

**Expected behavior**
The pokemon image has a background

**Screenshots**
![image](https://user-images.githubusercontent.com/39986236/104661497-89c48780-56c0-11eb-847f-2b768bfe7c8e.png)

**Additional context**

**Comment by NathNathNathNath** [comment]
Also happening for Swinub:
![image](https://user-images.githubusercontent.com/39986236/104662915-b62dd300-56c3-11eb-9a08-f04fd2a7c325.png)

**Comment by NathNathNathNath** [comment]
Confirmed that it isn't the same pokemon all the time, as I have seen multiple Solosis spawn recently (with the background), but have now seen that one without a background too:
![image](https://user-images.githubusercontent.com/39986236/104663064-1a509700-56c4-11eb-956a-46df6fcbfad8.png)

And it seems to be happening more frequently now

**Comment by oliver-ni** [comment]
The server was being migrated.
