### ISSUE TITLE
Double confirmation message on favouriting pokemon

### ISSUE THREAD

**Issue by NathNathNathNath** [oliver-ni/poketwo#121]
**Describe the bug**
There are two confirmation messages after favouriting pokemon using the method in the screenshot below

**To Reproduce**
See screenshot

**Expected behavior**
For there to be only one confirmation message

**Screenshots**
![image](https://user-images.githubusercontent.com/39986236/105013065-c41e8380-5a36-11eb-8000-52f0297bb906.jpg)

**Additional context**
n/a

**Comment by michaelsong4399** [comment]
Hello. This is an intended behavior. The two confirmation messages are placed in to state different things. 
`Favorited your 38 unfavorited pokemon.` tells you how many pokemon actually changed states, while 
`All selected pokemon favorited.` tells you that all your selected pokemons are set to the `Favorited` state. Note that the number of selected pokemons can be different from the number of pokemons that *need* to be favorited.

When I implemented this I wanted to split what the command has actually done with what the final results are. But I do see where this confirmation can be further clarified. We will consider that.
Thank you for your report!
