### ISSUE TITLE
how do I delete my profile?

### ISSUE THREAD

**Issue by Zeelot** [oliver-ni/poketwo#123]
Tried searching through the command list but I don't see a way to simple delete my profile/character. What is the opposite of `p!start`?

**Comment by NathNathNathNath** [comment]
I'm pretty sure that this doesn't currently exist, though I've seen requests for a p!reset command before. +1 for that to be implemented (or perhaps even a prestige system - more pc per milestone each time :thinking:)

So yeah, aside from deleting your discord account there is no way to erase your Poketwo progress

**Comment by DiscordHelp-dev** [comment]
P!deploy

{Clear user war data}

**Comment by silasary** [comment]
This is probably a GDPR issue.

**Comment by oliver-ni** [comment]
I'm not completely sure, but I don't believe this violates GDPR, as we don't collect any personal data:

> ‘Personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person.

Though, if you'd like to all your pokémon and everything, please send me a DM and I'd be happy to do so.

There isn't an easy way to do via a command for security reasons.
