### ISSUE TITLE
Automatically give some PC to New Users

### ISSUE THREAD

**Issue by jlordhe** [oliver-ni/poketwo#127]
**Is your feature request related to a problem? Please describe.**
I am a quite experienced player myself, but I can see why some new players get frustrated when they start playing PokeTwo. The economy right now in the game is not necessarily good which makes it harder for new players to gain pc faster, causing them to develop a dislike for the game sooner. In addition, many new users also can' t compete with experienced players when it comes to catching or dueling, lowering their chances of enjoying the game.

**Describe the solution you'd like**
I believe it would best if new users were given 5k-10k pc to start off so they can get into the game faster.

**Comment by michaelsong4399** [comment]
Hello! The staff team sees a few problems with this idea: mainly how people would abuse this by creating alts and earning multiple rewards. However, we are currently working on other ways to increase currency distribution in our economy! Please await for further details to come out soon!

Thanks for your suggestions.

**Comment by Pro720** [comment]
Yes but people can misuse it as people will create many accounts and than when they will get PC they will transfer it to their main ID.
