### ISSUE TITLE
Event Idea

### ISSUE THREAD

**Issue by jlordhe** [oliver-ni/poketwo#128]
**Is your feature request related to a problem? Please describe.**
I've noticed that quite a bit of people have begun to lose interest in the game with the majority of them being duelists like myself. 

**Describe the solution you'd like**
Make a megable event. 
14 day event similar to the Christmas festive Pokemon event. For each day, one currently unmegable Pokemon will be available to be mega evolved. After the event is over, these Pokemon can no longer be mega evolved. If they were mega-evolved during the event, then they will keep their mega evolution unless it is unmegaed by the trainer.

I am aware that you guys have a lot of other tasks like rewriting the bot, adding Gen 8, etc. For this reason, I'm completely fine with helping out designing the Pokemon along with a group of people I've asked. For the battles, you can just use the official sprites and not the new one. I've asked quite a bit of people and they seemed to like this idea.

**Comment by oliver-ni** [comment]
All the megas are already megable. I'd rather not add non-canon megas to the game, sorry.
