### ISSUE TITLE
Ability to redirect levelups

### ISSUE THREAD

**Issue by silasary** [oliver-ni/poketwo#13]
Levelup messages are large and sometimes get in the way of conversations.  It would be nice if we could redirect them to a dedicated channel, similar to how spawns are.

**Comment by oliver-ni** [comment]
We do have serversilence, but being able to redirect them could also be nice

**Comment by brenohq** [comment]
I will start work on that issue tomorrow.

**Comment by oliver-ni** [comment]
On second thought, I don't think this is a wide enough use case. If they will be redirected, might as well silence

**Comment by b0unse** [comment]
why is this not a feature members love the shouts but hate the interuption of chat
