### ISSUE TITLE
Mega Mewtwo X moves not Working

### ISSUE THREAD

**Issue by xdrc123124** [oliver-ni/poketwo#132]
The moves Me First, Disable, and Guard Swap doesn't work they just do 0 damage

To fix this just make sure the move does what the description says
Me first is supposed to use what move the opponents selected FIRST with 1.5x damage I believe, Disable Doesn't allow the opponent to use the move they used the last turn for 1-8 turns, Guard swap should switch defensive stats with the opponent

**Comment by bwl626** [comment]
all non healing status moves currently do not work.
