### ISSUE TITLE
Throw pokeballs to Catch Pokemon

### ISSUE THREAD

**Issue by ANTFOR7717** [oliver-ni/poketwo#133]
Instead of guessing the name to catch, instead throw pokeball with randomized chance of success?

**Comment by ShibePlanet** [comment]
Although this stays true to the original games, this would probably just make the game harder. You'd have to buy Pokeballs a lot, and there are not many ways to get PC at the moment.

**Comment by ANTFOR7717** [comment]
Interesting! I could see how it would make gameplay more difficult.
