### ISSUE TITLE
p!evolve requires you to input the pokemon number.

### ISSUE THREAD

**Issue by mangdani282** [oliver-ni/poketwo#142]
If I try to select a Pokémon and evolve it with p!evolve without inputting the number, it just says 'Congrats mangdani282!' and doesn't evolve my selected Pokémon. But, if I type p!evolve #, it works normally. This is annoying because sometimes I have to look through a long list of Pokémon to remember the number of the Pokémon I want to evolve.

![poketwo bug](https://user-images.githubusercontent.com/45503616/107123142-dc313800-6869-11eb-8b65-ff36c4ee8c05.PNG)

**Comment by unknownking31** [comment]
The bot currently is unstable and has limited functionality!! Many of these bugs will be resolved once full functionality returns and bot is stable again. Most of these bugs are known and I am pretty sure this bug is known too
