### ISSUE TITLE
Dex populating through evos/trade

### ISSUE THREAD

**Issue by paynejordand** [oliver-ni/poketwo#159]
Currently the Pokedex only updates if you catch the pokemon as a wild spawn. 
It would be nice if it could update whenever you evolve a pokemon or have a trade evolution.

Example:
I don't have Jigglypuff or Wigglytuff registered in the Dex.
I catch a wild Jigglypuff and evolve it with a moon stone.
Now Jigglypuff is registered in the Dex but not Wigglytuff.

**Comment by michaelsong4399** [comment]
Hello. Please refer to #144. Thanks.

**Comment by paynejordand** [comment]
I figured it was a design choice. Thank you :)
