### ISSUE TITLE
Pagination on trading

### ISSUE THREAD

**Issue by thekevinava** [oliver-ni/poketwo#32]
**Describe the bug**
When you add more than 15 pokemons on trading, it shows an error that are more than 1024 characteres, the system doesnt add pagination

**Comment by oliver-ni** [comment]
There is pagination. It might occasionally overflow, though

**Comment by thekevinava** [comment]
I think last update you uploaded, the pagination on trading is wrong, because it doesnt separate the pokemons by pages
