### ISSUE TITLE
Can't select pokemon

### ISSUE THREAD

**Issue by TheBlazingNdrman** [oliver-ni/poketwo#51]
I used redeem to get a Rayquaza, now when i do p!select 0 to select my greninja, it selects Rayquaza. This might have happened with another pokemon before, I havent tried selecting it in a while.
It should have just selected Greninja.
![image](https://user-images.githubusercontent.com/72932939/96149295-c40a6700-0ece-11eb-8cb7-aa02faf43404.png)
Ignore the nickname and the other person, I didn't choose them

**Comment by oliver-ni** [comment]
Please use `p!reindex` to update the numbering of your pokémon

**Comment by TheBlazingNdrman** [comment]
ok thanks
