### ISSUE TITLE
Base prices?

### ISSUE THREAD

**Issue by Startemynx** [oliver-ni/poketwo#53]
So, for the market, what if there were a command to help people figure out how to price their pokemon? They would do something along the lines of p!pricecheck <pokemon> and it would give a base price for that species, as well as recommendations for add-ons for things such as high ivs and shiny. This would probably be a LOT of work, but I think it would be really helpful to flatten the extreme price curve in the markets. I’d personally be willing to contribute to said project if it goes through.

**Comment by oliver-ni** [comment]
This is outside the scope of the bot. Feel free to write another tool to do this.
