### ISSUE TITLE
Battles don't seem to work

### ISSUE THREAD

**Issue by jorgejarai** [oliver-ni/poketwo#56]
**Describe the bug**
I've been trying to battle with some friends and we cannot do anything after inviting another person. The bot seems unresponsive when trying to add Pokémon to the battle team, but when it comes to other commands (like `p!pokemon` or `p!moves`), they work as usual.

**To Reproduce**
Me: `p!battle  <somebody>`
_(They accept)_
Me: `p!add <some Pokémon>`
_(The bot doesn't reply)_
They: `p!add <another Pokémon>`
_(Nothing as well)_
Me: `p!moves`
_(The bot replies and shows my selected Pokémon moves)_
They: `p!moves`
_(The bot replies again)_

**Expected behavior**
The bot should return some kind of answer, whether the Pokémon was added to the battle team, it doesn't exist or something like that.

**Screenshots**
[https://imgur.com/a/jaSN6rR](url)

**Additional context**

**Comment by kyle-he** [comment]
You need to add the pokemon number in your pokedex, not the name.  Use `p!dex` to check what number each of your pokemon are.

**Comment by jorgejarai** [comment]
It would've been nice if that were in the command help, but thanks anyway.
