### ISSUE TITLE
Vote Reminders Sent Twice

### ISSUE THREAD

**Issue by DevilJamJar** [oliver-ni/poketwo#59]
**Describe the bug**
DM top.gg vote reminders are sent twice at once, meaning that the same message is sent within seconds of the first.

**To Reproduce**
Vote for Pokétwo and wait 12 hours to receive a vote reminder. It will be sent twice within seconds, pinging you twice.

**Expected behaviour**
DM is sent once every 12 hours to let you know you need to vote for the bot again.

**Screenshots**
In the below screenshot, both messages were sent at 19:43, at the same time precisely.
[<img src="https://cdn.discordapp.com/attachments/750483027590643773/775816482554380328/unknown.png">](https://cdn.discordapp.com/attachments/750483027590643773/775816482554380328/unknown.png)

**Additional context**
This only started happening recently, within the past two days. Only one message is sent once you have voted and received your reward box, the duplication only occurs when the reminder is sent.

**Comment by Shirra2006** [comment]
True, sometimes it only sends one reminder message to me, sometimes it sends 2.

**Comment by DevilJamJar** [comment]
Closing this since it seems to be fixed.
