### ISSUE TITLE
Christmas Event

### ISSUE THREAD

**Issue by Shirra2006** [oliver-ni/poketwo#63]
Since the Halloween Event was nice and some people wanted more events, I think the best chance is a Christmas Event!

In this event, you collect Ice candy (Light blue _Rare Candy_)
### Quests

- Catch 20 water type  pokemons [0/20]

- Catch 20 ice type pokemons [0/20]

- Buy 5 water type pokemons [0/5]

- Trade 5 ice type pokemons [0/5]

- Catch 10 Shellder [0/10]

- Catch 10 Spheal [0/10]

- Catch 10 Vanillite [0/10]

- Catch 10 Swinub [0/10]

- Catch 10 Horsea [0/10]

- Catch 10 Poliwag [0/10]

- Catch 10 Lotad [0/10]

- Catch 10 Feebas [0/10]

### Special Pokemons

- New pokemons that can spawn (only in the event): [Wash Rotom](https://cdn.bulbagarden.net/upload/thumb/e/ea/479Rotom-Wash.png/600px-479Rotom-Wash.png), [Pikachu Belle](https://cdn.bulbagarden.net/upload/thumb/f/f0/025Pikachu-Belle.png/100px-025Pikachu-Belle.png), [White Kyurem](https://cdn.bulbagarden.net/upload/thumb/8/81/646Kyurem-White.png/600px-646Kyurem-White.png).

- Pokemons with spawn rate higher than normal: Shellder, Alolan Sandshrew, Alolan Vulpix, Glaceon, Articuno, Manaphy, Phione.

### Shop

- Chirstmas Box: would get mythical, legendary, alolan forms, shinies, shards, redeems and (Price: **30 Ice Candy**).

- Wash Rotom (Price: **150 Ice Candy**)

- Pikachu Belle (Price: **300 Ice Candy**)

- White Hyurem (Price: **600 Ice Candy**)

- Icy Snow [Vivillon](https://cdn.bulbagarden.net/upload/thumb/6/6c/666Vivillon-Icy_Snow.png/100px-666Vivillon-Icy_Snow.png) (Price: **50 Ice Candy**)

- Marine [Vivillon](https://cdn.bulbagarden.net/upload/thumb/4/4d/666Vivillon-Marine.png/100px-666Vivillon-Marine.png) (Price: **50 Ice Candy**)

- Polar [Vivillon](https://cdn.bulbagarden.net/upload/thumb/a/a6/666Vivillon-Polar.png/100px-666Vivillon-Polar.png) (Price: **50 Ice Candy**)

- Tundra [Vivillon](https://cdn.bulbagarden.net/upload/thumb/9/9a/666Vivillon-Tundra.png/100px-666Vivillon-Tundra.png) (Price: **50 Ice Candy**)

### Voting
By voting for the bot and the official server, you can get 5 Ice Candy each time, 10 at the weekends, 15 on the 24/12 and 20 on the 25/12.

**Comment by SoulBurner1009** [comment]
nice bro whats the date of event?

**Comment by SoulBurner1009** [comment]
well i am banned from poketwo server due to some harsh staff members of server.
i contacted a server to unmute me from trading channel but he directly banned me 
my discord id - Soul Burner#1009

**Comment by SoulBurner1009** [comment]
#Need Justice

**Comment by oliver-ni** [comment]
We do have something planned, but we're not accepting community suggestions on events at this time.
