### ISSUE TITLE
ETERNATUS

### ISSUE THREAD

**Issue by AumTheBest1** [oliver-ni/poketwo#70]
ADD ETERNATUS

THATS LITERALLY THE GOD POKEMON ADD IT OLIVER PLS

**Comment by Shirra2006** [comment]
Uhm.....that is a gen 8 pokemon and it is coming soon! (not yet)
It has already added to the [to-do list ](https://github.com/oliver-ni/poketwo/projects/3) and that is quite similar to spamming (since u already requested it once).
