### ISSUE TITLE
Starter Pokemons are not listed as _caught_

### ISSUE THREAD

**Issue by Erigers** [oliver-ni/poketwo#72]
When listing pokedex, starter pokemon status is not caught, which I believe is a bit misleading and confusing since we already have that pokemon.

**Comment by shadow5555727** [comment]
I think that Pokemon is chosen not caught right? So I don't think it needs to be listed in Dex

**Comment by Erigers** [comment]
Technically you can choose a pokemon, but if it needs to "rest", meaning you switch your first pokemon, it's supposedly going into a pokeball, thus caught, in my opinion. Also, talking from experience from other poke games, it's the same concept.

Another point of view, people like to populate their pokedex and this means we would need to get the starter pokemon for a second time, which is not very comfortable :/

**Comment by NathNathNathNath** [comment]
People who are aiming to complete their pokedex will not be worrying about catching a starter pokemon. They will likely catch dozens in their quest to complete dex, minimum

I do not think this is a bug. Or even if it technically is, it isn't important or necessary to fix.

**Comment by Erigers** [comment]
👍

**Comment by cefifer** [comment]
Maybe I just missed how, but I switched out my starter for a different Pokémon for a bit and now I can’t switch back to it because the Pokémon isn’t registered in the dex.
