### ISSUE TITLE
Misleading "Congratulations" message on catching event pokemon

### ISSUE THREAD

**Issue by NathNathNathNath** [oliver-ni/poketwo#78]
**Describe the bug**
The message states that I have caught 10 festive torchics, which isn't the case.

**To Reproduce**
Catch 9 "normal" forms, then 1 event form.

**Expected behavior**
The message should not have the second "festive" word.

**Screenshots**
![image](https://user-images.githubusercontent.com/39986236/103166319-c6ffcd00-4818-11eb-9f28-2c341efae640.png)

**Additional context**
n/a

**Comment by oliver-ni** [comment]
Fixed in #79
