### ISSUE TITLE
How constraint is this project?

### ISSUE THREAD

**Issue by genofire** [oliver-ni/poketwo#9]
would you merge?
- abstraction to support other messenger systems (e.g. xmpp, telegram) 
- support other databases the mongo to store data

**Comment by oliver-ni** [comment]
Supporting other databases would be nice, but right now the bot code is quite mixed in with the mongodb stuff, so it'd take a bit of refactoring to fix that.

Other messaging systems probably no for now. That'd require almost all the code to be deconstructed
