### ISSUE TITLE
Possible to buy held items even if selected pokemon already has one equipped 

### ISSUE THREAD

**Issue by unknownking31** [oliver-ni/poketwo#98]
**Describe the bug**
Its possible to buy held items even if your pokemon has one already equipped  and bought held will replace already equipped ones and you will lose 150pc

**To Reproduce**
Select a pokemon with  a held item already equipped and/or buy any random held item multiple times 

**Expected behavior**
Instead of just replacing already equipped held item bot should reply with something like:-"The selected pokémon is already holding an item. Please select a different pokémon using **p!select** and try again." and it should cancel the purchase

**Screenshots**
![IMG_20210106_221904](https://user-images.githubusercontent.com/77022549/103807066-e3eb9a00-507b-11eb-823b-798abea27839.jpg)

**Comment by unknownking31** [comment]
This issue can also be solved if we add an item inventory/bag to store item (A bag would be more useful if we get more held items) 
There are two ways we can fix this issue by adding an item inventory:-
       2a. Bought held items will be directly stored in bag/inventory and one need to manually equip them tho(That will automatically solve this issue) 
                                     OR
       2b. Held items will only be stored in bag if ur selected pokemon is already holding an item otherwise held items will be equipped to your selected pokemon(most convenient way imo)

**Comment by oliver-ni** [comment]
This is intended behavior. An inventory is under consideration for the rewrite.

**Comment by unknownking31** [comment]
Oh ok. I was not sure whether it was a known bug or intentional and no one was there to solve my misconception because they didn't knew about it either(atleast people I asked),still I reported that because I thought if it was a bug some people could lose items because they forgot their selected pokemon has an item equipped and didnt knew that one can buy items even if selected pokemon has one(Thats how I realised that this behavior exist  hehe) or even evolve a pokemon(super situational but still possible)  Anyways, I am sorry.

**Comment by NathNathNathNath** [comment]
I don't want to speak for Oliver because this is his project of course - but as a career software tester, raising potential issues is a good thing even if it turns out not to actually be one. No need to say sorry, imo :)
